title: Aleksei Lobanov
author: Lobanov Aleksei
logo: /assets/img/logo.png
description: Personal blog of Aleksei Lobanov
google_analytics:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

collections:
  bookmarks:
    output: true
  logs:
    output: true

plugins:
  - jemoji
